lxqt/lxqt-globalkeys

daemon/core.cpp

In three cases char arrays created on the heap were only deleted if no error occurred afterwards. This was now fixed by also deleting them in the error handling paths.

Fix three memory leaks in daemon error handling

---

CMakeLists.txt
daemon/CMakeLists.txt

The daemon uses exceptions. We enable them but only for the daemon target.

Use LXQtCompilerSettings CMake module

---

config/edit_action_dialog.cpp

This fixes the following bug:
* Open the globalkeys config
* Open the edit dialog (via `Add` or `Modify`, it doesn't matter), click one of the two radio boxes (Command vs. D-Bus) and close it again
* Press `Add`
Actual behavior:
* One of the two radio boxes is selected
Expected behavior:
* Neither of them is selected
The problem is that just doing `setChecked(false)` does not do anything if this part of an exclusive group. Turning that exclusivity off temporarily fixes this.

fix reseting the state of the edit dialog

---

config/translations/lxqt-config-globalkeyshortcuts_fr.ts

The string was missing because its source had been incorrectly edited.
Thanks!

Fix untranslated string in French translation

---

daemon/core.cpp
daemon/core.h

..to avoid using of deprecated QDBusConnectionInterface::serviceOwnerChanged() signal
Fixes lxde/lxqt#1098

daemon: Use QDBusServiceWatcher

---

daemon/core.cpp

Avoid assignment of a non-const pointer to a const pointer and the
consequent container detach.

Use const iterators

---

config/main.cpp

lxqt-config-globalkeys: set Qt::AA_UseHighDpiPixmaps to true

---

config/edit_action_dialog.cpp

When the dialog box was displayed, the radio buttons were not
initialized correctly if a client-type action was to be modified.
This PR resolves issue lxde/lxqt#1376

Fixes wrong radio buttons when changing shortcuts

---

cmake/lxqt_globalkeys-config.cmake.in
cmake/lxqt_globalkeys_ui-config.cmake.in

CMP0024 OLD behavior will be deprecated.
Also use the LXQT_GLOBALKEYS_LIBRARY_NAME instead of hardcoding the value.

Handle CMake CMP0024

---

daemon/core.cpp

When user presses a key, but this key was not previously registered as a
shortcut, the shortcut map is polluted with "" entry.
This could cause an error when the shortcut is not set after clicking OK in the
keybinging editing dialog and you are told that shortcut "" is being used
instead (in the logs).

Avoid polluting the the shortcut map when shortcut is pressed and not registed

---

daemon/core.cpp

This is the solution 1.2. which I described in issue lxde/lxqt#1259 on 3.12.2017.
This solution required the least changes in the source code.
You can merge the source code as it is. However, if you prefer a different name for the meta keys, e. g."meta-left" and "meta-right" instead of the X11 symbol names, then I can make the changes before merging.

Super keys

---

xdg/globalkeyshortcuts.conf

Let's add a default shortcut to call xdg-screensaver and lock the
screen.
Proposing: Ctrl+Alt+l in relation to Ctrl+Alt+d

Add shortcut for lockscreen

---

client/CMakeLists.txt
client/client.cpp
config/CMakeLists.txt
config/actions.cpp
config/default_model.cpp
config/edit_action_dialog.cpp
daemon/CMakeLists.txt
daemon/client_action.cpp
daemon/command_action.cpp
daemon/core.cpp
daemon/main.cpp
daemon/string_utils.cpp
ui/CMakeLists.txt

* Disables automatic conversions from 8-bit strings (char *) to unicode
QStrings.
* Disables automatic conversion from QString to 8-bit strings (char *).
* Disables automatic conversions from QByteArray to const char * or const
void *.
* Disables automatic conversions from QString (or char *) to QUrl.
* Use QStringBuilder for more efficient string creation.
It make us aware of string and encoding conversions.

Don't use automatic string conversions

---

config/main_window.ui

Reverted the change. Fixes lxqt/lxqt-globalkeys/issues/107

Don't rename a widget or a class without a full refactoring.

---

config/main_window.cpp
config/main_window.ui
daemon/core.cpp

NOTE: IMHO, the config file of lxqt-globalkeys is set in weird way by the current code. Qt handles global and user config files automatically. Or I'm missing something here?

Remember config window size on exiting

---

daemon/core.cpp
daemon/core.h
daemon/main.cpp

@wxl, @agaida  Please, test this thoroughly ...

daemon: Use XDG hierarchy if no config file given on command line

---

daemon/core.cpp
daemon/core.h
daemon/main.cpp
xdg/CMakeLists.txt

same as for session: make it easy for distributions to provide own configurations

WIP: move shortcuts config fom /etc/xdg/lxqt to /usr/share/lxqt

---

daemon/core.cpp

However, the same shortcut key can be repeated when one of the other parameters is different.

Prevent exactly the same shortcut from being repeated at startup

---

daemon/core.cpp
daemon/core.h

Fixes https://github.com/lxqt/lxqt-globalkeys/issues/134
Suppose that the user has started the daemon for the first time and then, disabled the shortcut `XY` that comes from a global config file. Now, the user config file includes something like:
```
[XY.9]
Comment=My Shortcut
Enabled=false
Exec=runThis
```
The suffix ".9" depends on when the section is read. On the other hand, a global config file may contain:
```
[XY.1]
Comment=My Shortcut
Enabled=true
Exec=runThis
```
The next time the daemon is started, there's no guarantee that it reads the user section before the global one because `QSettings` sorts sections before returning them (see Qt → qsettings.cpp → QConfFileSettingsPrivate::children). But if it reads `[XY.1]` first, then the value of `Enabled` will be `true`, which means that …

Fixed loading of settings

---

config/main_window.cpp
config/main_window.h
config/main_window.ui
daemon/core.cpp

(1) Don't bring back removed shortcuts with the next session. Previously, those default shortcuts that were removed by the user were restored with the next daemon startup.
(2) A Default button is added, which removes all user-defined shortcuts and restores the default ones, by showing a prompt dialog.
Closes https://github.com/lxqt/lxqt-globalkeys/issues/135
@agaida Please be cruel while testing ;)

Better handling of default shortcuts

---

config/main_window.ui

Add a "comment" attribute which acts as a translation context.
<hr>
Frankly speaking, I need a separate context here for "None" for Russian translation. Currently it matches the context of the same string from `ScreenGrub`, so I can't translate them differently. I've already tried to achieve this by PR #101, but that way was actually erroneous.
It might be a bit confusing to give a different context to a single string, so I decided to set it for all others string of the same group as well.
Note that another approach to the issue is to rename the whole class `MainWindow` to something different, but that would be something over the top IMHO.
Also it is possible to resolve the issue by tweaking Weblate's settings to prevent forced translation sharing between different components.
PS: sorry …

ui: add some translation context for multipleActionsBehaviour values

---

xdg/globalkeyshortcuts.conf

Launch the lxqt-config-monitor tool when the Display key (XF86Display) key is pressed.

Add shortcut to configure display

---

daemon/core.cpp

When `Core::addOrRegisterClientAction` was called by `Core::addClientAction`, it grabbed keys without checking whether shortcuts were enabled or not and so, it didn't let the same shortcuts be used by apps. A simple check fixes the problem.
Fixes https://github.com/lxqt/lxqt-globalkeys/issues/173

Do not grab keys of disabled client actions

---

config/shortcut_selector.cpp

It was caused by https://github.com/lxqt/lxqt-globalkeys/commit/6d53cf85f2de5da2f160b00105f9bb4eda11322e

Fixed a regression in shortcut selector

---

daemon/core.cpp

Otherwise, after a recent libx11 commit, the app might exit with code 1 (see the comment inside the code).
Closes https://github.com/lxqt/lxqt-globalkeys/issues/247

Don't require Xlib to behave synchronously

---

CMakeLists.txt
config/CMakeLists.txt

KWindowSystem isn't an source code dependency.
liblxqt brings KWindowSystem in as an INTERFACE_LINK dependency.

Remove KWindowSystem as direct dependency

---

config/main_window.ui

Sets the window icon of lxqt-config-globalkeyshortcuts to preferences-desktop-keyboard

Add theme icon to config/main_window.ui

---

config/main_window.ui

- Added 'window-close' icon to 'Close'
`lxqt-config-globalkeys` is distinct in that it doesn't use QDialogButtonBox, but instead regular QPushButtons for its dialog buttons. The lack of icons looked odd.
The other dialog button missing an icon is "Default". It should have an icon, but there may be no suitable one.

Add icons to dialog buttons

---

xdg/globalkeyshortcuts.conf

Cleanup `/usr/share/lxqt/globalkeyshortcuts.conf`.
Prior attempt: https://github.com/lxqt/lxqt-globalkeys/pull/272
Note: this does _not_ alter user settings.
1. Rename/move `~/.config/lxqt/globalkeyshortcuts.conf`
2. Restart "Global Keyboard Shorcuts" from Session Settings
3. Launch `lxqt-config-globalkeys`
You should see the default preconfigured shortcuts.

Cleanup default globalkeyshortcuts.conf

---

config/main_window.cpp

Previously the table view jumped to the next cell when scrolling. IMO smooth scrolling is much more readable.

Config UI: Enable smooth scrolling for table view
